// DO NOT MODIFY THIS FILE, IT WILL BE OVERRIDE!!!
#ifndef _KENDRYTE_IDE_FLASH_MANGER_OUT_H
#define _KENDRYTE_IDE_FLASH_MANGER_OUT_H

#define peaple_START 0x81000000
#define peaple_END 0x81003000
#define peaple_SIZE 11485

#endif // _KENDRYTE_IDE_FLASH_MANGER_OUT_H

